### ISSUE TITLE
'import' instead of 'require'?

### ISSUE THREAD

**Issue by samjross** [chegele/AutoGitUpdate#1]
I probably would have used this, but because it uses imports instead of 'require', I assume I'd have to get some kind of build step to make this work. Doesn't seem ideal.

**Comment by chegele** [comment]
Import is a feature of ECMAScript modules, and is supported in node.js v13+. You can read more about it @ https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling. 

If you want to use this module without the import/export statements you would just need to convert the imports to require statements and use the module exports for the main class. 
```
import path from 'path'; //TO const path = require('path');
import fs from 'fs-extra'; //TO const fs = require('fs');

export default class AutoGitUpdate { //TO module.exports = {
```

This has already been done on a forked version of this repository.
