### ISSUE TITLE
Error:  Cannot copy 'C:\Users\User\Nodejs_Projects\auto-update' to a subdirectory of itself, 'C:\Users\User\Nodejs_Projects\auto-update\tmp\AutoGitUpdate\backup\'.

### ISSUE THREAD

**Issue by XNexusPrimeX** [chegele/AutoGitUpdate#2]
Congratulations on the module, it is simple to use, and until you download the update, but as I understand it, there is a part that he tries to backup the old version before installing the new one, only he tries to move the pasta itself into hers... confused...

Is there a way to fix this or disable this backup?

the error:
```
[14/05/2021 13:08:42] ERROR   Auto Git Update - Error updating application
[14/05/2021 13:08:42] ERROR   Error: Cannot copy 'C:\Users\User\Nodejs_Projects\auto-update' to a subdirectory of itself, 'C:\Users\User\Nodejs_Projects\auto-update\tmp\AutoGitUpdate\backup\'.
    at C:\Users\User\Nodejs_Projects\auto-update\node_modules\fs-extra\lib\util\stat.js:83:17
    at C:\Users\User\Nodejs_Projects\auto-update\node_modules\fs-extra\lib\util\stat.js:38:16
    at callback (C:\Users\User\Nodejs_Projects\auto-update\node_modules\graceful-fs\polyfills.js:299:20)
    at FSReqCallback.oncomplete (fs.js:184:5)
```

**Comment by chegele** [comment]
> 
> 
> Congratulations on the module, it is simple to use, and until you download the update, but as I understand it, there is a part that he tries to backup the old version before installing the new one, only he tries to move the pasta itself into hers... confused...
> 
> Is there a way to fix this or disable this backup?
> 
> the error:
> 
> ```
> [14/05/2021 13:08:42] ERROR   Auto Git Update - Error updating application
> [14/05/2021 13:08:42] ERROR   Error: Cannot copy 'C:\Users\User\Nodejs_Projects\auto-update' to a subdirectory of itself, 'C:\Users\User\Nodejs_Projects\auto-update\tmp\AutoGitUpdate\backup\'.
>     at C:\Users\User\Nodejs_Projects\auto-update\node_modules\fs-extra\lib\util\stat.js:83:17
>     at C:\Users\User\Nodejs_Projects\auto-update\node_modules\fs-extra\lib\util\stat.js:38:16
>     at callback (C:\Users\User\Nodejs_Projects\auto-update\node_modules\graceful-fs\polyfills.js:299:20)
>     at FSReqCallback.oncomplete (fs.js:184:5)
> ```

In the configuration you define a temp location for downloading the update and storing these backups. If you set this to something outside of the project, your issue will be resolved. 

Alternatively, if you would like to disable this feature you can fork the repository and comment out lines 139-142 in the index.js file. Please let me know if either of these are viable solutions :)
